In [1]:
import tensorflow as tf
import numpy as np

def tensor_creation():
    print("=== Tensor Creation ===")
    scaler = tf.constant(5)
    vector = tf.constant([1, 2, 3])
    matrix = tf.constant([[1, 2], [3, 4]])
    tensor_3d = tf.constant([[[1], [2]], [[3], [4]]])

    print(f"Scaler: {scaler}")
    print(f"Vector: {vector}")
    print(f"Matrix: {matrix}")
    print(f"Tensor-3D: {tensor_3d}")

    np_array = np.array([[10, 20], [30, 40]])
    tensor_from_np = tf.convert_to_tensor(np_array)
    print(f"Tensor From NumPy: {tensor_from_np}")


def tensor_manipulation():
    print("=== Tensor Manipulation ===")
    a = tf.ones((2, 3))
    b = tf.zeros((2, 3))
    c = tf.fill((2, 3), 7)

    print(f"Ones: {a}")
    print(f"Zeros: {b}")
    print(f"Fills: {c}")

    reshaped = tf.reshape(c, (3, 2))
    print(f"Reshaped to (3,2):\n{reshaped}")

    print(f"First row of a: {a[0]}")
    print(f"Element at (1,2): {a[1, 2].numpy()}")

    concat = tf.concat([a, b], axis=0)
    print(f"Concatenated (axis=0):\n{concat}")


def math_operations():
    print("=== Math Operations ===")
    x = tf.constant([2.0, 4.0, 6.0])
    y = tf.constant([1.0, 3.0, 5.0])

    print(f"x + y = {tf.add(x, y)}")
    print(f"x - y = {tf.subtract(x, y)}")
    print(f"x * y = {tf.multiply(x, y)}")
    print(f"x / y = {tf.divide(x, y)}")
    print(f"Dot product = {tf.tensordot(x, y, axes=1)}")

    mat = tf.constant([[1], [2], [3]])
    vec = tf.constant([4, 5, 6])
    print(f"Broadcasted addition:\n{mat + vec}")


@tf.function
def compute_graph(a, b):
    return tf.sqrt(tf.add(a ** 2, b ** 2))  # Hypotenuse


def dynamic_sum(n):
    total = tf.constant(0)
    for i in range(n):
        total += i
        tf.print("Step", i, "Current total:", total)
    return total


def run_pipeline():
    tensor_creation()
    tensor_manipulation()
    math_operations()

    print("=== Computation Graph ===")
    result = compute_graph(3.0, 4.0)
    print(f"Hypotenuse (graph mode): {result}")

    print("=== Eager Execution Example ===")
    final_sum = dynamic_sum(5)
    print(f"Final sum: {final_sum.numpy()}")


if __name__ == "__main__":
    run_pipeline()


=== Tensor Creation ===
Scaler: 5
Vector: [1 2 3]
Matrix: [[1 2]
 [3 4]]
Tensor-3D: [[[1]
  [2]]

 [[3]
  [4]]]
Tensor From NumPy: [[10 20]
 [30 40]]
=== Tensor Manipulation ===
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Fills: [[7 7 7]
 [7 7 7]]
Reshaped to (3,2):
[[7 7]
 [7 7]
 [7 7]]
First row of a: [1. 1. 1.]
Element at (1,2): 1.0
Concatenated (axis=0):
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
=== Math Operations ===
x + y = [ 3.  7. 11.]
x - y = [1. 1. 1.]
x * y = [ 2. 12. 30.]
x / y = [2.        1.3333334 1.2      ]
Dot product = 44.0
Broadcasted addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]
=== Computation Graph ===
Hypotenuse (graph mode): 5.0
=== Eager Execution Example ===
Step 0 Current total: 0
Step 1 Current total: 1
Step 2 Current total: 3
Step 3 Current total: 6
Step 4 Current total: 10
Final sum: 10
